# Copyright (c) 2017-2018 Science and Technology Facilities Council

# All rights reserved.

# Modifications made as part of the fparser project are distributed
# under the following license:

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:

# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.

# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.

# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
language: python
python:
  - 2.7
  - 3.6
# command to install dependencies
before_install:
  - pip install codecov
install:
  - "pip install ."
script:
  # fparser should work even under limited terminal conditions
  # (this is only relevant for versions before Python 3.7).
  - export LC_ALL=POSIX
  - coverage run --source=fparser -m py.test
  - coverage report -m
after_success:
  - codecov
# Configure travis to deploy to the pypi server when a new
# version is tagged on master
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "BgJwNpWTZdUkczQ7CVoynjisxuTm5bqfTt1CyNYS891vQ99ne40p8po8MujHvM2cU8lq9UegvZj3K+SITEZ2CkD5ceQ1mmBowc9OTahBdwMkRHMKC24dxs9wsg4zIdzli8SCwxeqFodfCQX6tfr3E77nEWBd+3ktgQlh11/Xan9g304NqldA4f53OZz7NWLX0F3KXpZ2BSYf/IyJbek1MFQ6d+D7XKeVvM2tVle/FuIv4/1kbVKMzB0BfdWPFJoqz8nMZ5H5VajVgSkwTB0NlPZpyWlz0ZIYNDIQCtY0Q7ELND4t+Ts1TOGW30j4c7LqqySAVHcSBRU4NJz0oY3TQjGwC8dkjC1+X/zUMgZ1K3jKLZm0WqURMTEXlq2ewfSFgngvj+q9Zt4IlSxsZmiXHkLSi5zv2M/FIMSZrMrAZccr/Utv29+eHnCLoxsqSuCUnIw4pnacRmkwRbVnd2mmmbdW2d9hlAkL7W1+14hpgssGYfC0pTcQCZEdFfbpzJUjssRCEIi9ahqjwX+mvBVKQxDt95EcEGx7nouCYmySwkhtIkuKyBCrdyb7LdRn4xdmCPLKzgGeQAzbuHdentZogQ/yxgTexIfoWwDboSDs4n64/ZeMAIuE8XqxqEhHiiCoY+hxEKLf45E3XClbY1f0hVRG1ZBHnK1qPKPEKk36Nr4="
  on:
    tags: true

